### ISSUE TITLE
Duplicate Title in Appendix

### ISSUE THREAD

**Issue by tomjw64** [Connexions/cte#24]
This duplicate title appears in the raw statistics HTML within Appendix F. See image below:

<img width="701" alt="screen shot 2016-06-01 at 1 37 22 pm" src="https://cloud.githubusercontent.com/assets/1285308/15721368/4dd9cb2c-27fe-11e6-8a87-0ba5b84b2c1c.png">

**Comment by tomjw64** [comment]
@reedstrm is this a transform or content issue?

**Comment by reedstrm** [comment]
The raw content contains both a section title and a table caption that contain the same text "Symbols and [Tt]heir Meanings" (note the diff. cap. of 'their'). I think this is part of the 'fixing table/figure etc. captions and titles' issue.
